<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>

    <style>
      * {
        box-sizing: border-box;
      }

      .wrapper {
        outline: 1px solid red;
        width: 200px;
        height: 200px;
      }

      .child {
        outline: 1px solid green;
        width: 100%;
        height: 100%;
        padding: 5px;
      }
    </style>
  </head>
  <body>
    <div class="wrapper">
      <div class="child"></div>
    </div>

    <script>
      function fetchUrl(url) {
        return new Promise((resolve, reject) => {
          function myFetch(attempt) {
            fetch(url)
              .then((res) => {
                if (!res.ok) {
                  if (attempt === 5) {
                    reject("Ошибка!");
                  } else {
                    myFetch(attempt + 1);
                  }
                } else {
                  resolve(res);
                }
              })
              .catch((e) => {
                if (attempt === 5) {
                  reject("Ошибка!");
                } else {
                  myFetch(attempt + 1);
                }
              });
          }

          myFetch(1);
        });
      }

      /* Необходимо реализовать функцию fetchUrl, которая будет использоваться следующим образом. Внутри fetchUrl можно использовать условный метод fetch, который просто возвращает Promise с содержимым страницы или вызывает reject */
      fetchUrl("https://google/com")
        .then((res) => console.log("Ура! Тело -", res))
        .catch((e) => {
          console.log(`${e}`);
        }); // сatch должен сработать только после 5 неудачных попыток получить содержимое страницы внутри fetchUrl
    </script>
  </body>
</html>
